version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fluxo_prod_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fluxo_prod
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: ./server
    container_name: fluxo_prod_server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_USER=admin
      - DB_HOST=db
      - DB_NAME=fluxo_prod
      - DB_PASSWORD=password
      - DB_PORT=5432
      - PORT=3000
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db

  client:
    build: .
    container_name: fluxo_prod_client
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/server
    depends_on:
      - server

volumes:
  postgres_data:
